version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: oms-postgres
    environment:
      POSTGRES_DB: order_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: order-management-service
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/order_management
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"

volumes:
  postgres_data:
